global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'discord-webhook'
receivers:
- name: 'discord-webhook'
  discord_configs:
  - webhook_url: 'https://discord.com/api/webhooks/1462138509589479599/WxJiYC0mBfHftcZShVt4pTKHM5HVkMsh4DMXlhdQXBF0BIoLoSpEgn1XJC9QVOB28UJw'
    send_resolved: true
