{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "SLA / Dostępność",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status!~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Błędy Aplikacji",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{status=~\"4..|5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zużycie CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Całkowity Ruch (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Całkowity Ruch"
    }
   ]
  },
  {
   "title": "Popularność Endpointów",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "sum by (handler, method) (rate(http_requests_total{handler=~\"/books.*\", handler!=\"/books/register\"}[1m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Rozkład Opóźnień (Latency Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zużycie RAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Użycie Pamięci" }
   ]
  }
 ]
}